# Generated by Django 4.0.3 on 2022-03-22 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apppedido', '0002_rename_id_repartdir_repartidor_id_repartidor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repartidor',
        ),
    ]
