# Generated by Django 4.0.3 on 2022-03-22 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apppedido', '0004_repartidor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repartidor',
            old_name='id_repartidor',
            new_name='id_repartdir',
        ),
    ]
