# Generated by Django 4.0.3 on 2022-03-22 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apppedido', '0005_rename_id_repartidor_repartidor_id_repartdir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repartidor',
            old_name='id_repartdir',
            new_name='id_repartidor',
        ),
    ]
