# Generated by Django 4.0.3 on 2022-03-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppedido', '0007_alter_repartidor_num_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='num_celular',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
