# Generated by Django 4.0.3 on 2022-03-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppedido', '0008_alter_cliente_num_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repartidor',
            name='id_repartidor',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
