# Generated by Django 4.0.3 on 2022-03-22 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apppedido', '0009_alter_repartidor_id_repartidor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repartidor',
            name='pedido',
        ),
    ]
