# Generated by Django 4.0.3 on 2022-03-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppedido', '0011_pedido_repartidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repartidor',
            name='id_repartidor',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
