# Generated by Django 4.0.3 on 2022-03-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppedido', '0012_alter_repartidor_id_repartidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='repartidor',
            name='id_repartidor',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
