# Generated by Django 4.0.3 on 2022-03-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppedido', '0013_alter_producto_id_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('nombre', models.CharField(max_length=40)),
                ('camadao', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
