# Generated by Django 4.0.3 on 2022-03-25 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apppedido', '0015_rename_camadao_curso_camada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='num_celular',
            new_name='celular',
        ),
    ]
