# Generated by Django 4.0.3 on 2022-03-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apppedido', '0017_alter_cliente_celular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
    ]
