# Generated by Django 4.0.3 on 2022-03-28 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apppedido', '0020_remove_pedido_cliente_alter_cliente_celular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='producto',
        ),
    ]
